Repository ubuntu/yaru, pull requests merged in 2021-05, with the labels that each got.

#2832 Disable gresource meson option
  meson_options.txt
Labels: Area: build

#2835 Add symbolic Snap app and mimetype icons
  icons/Suru/scalable/apps/snap-symbolic.svg
  icons/Suru/scalable/mimetypes/application-vnd.snap-symbolic.svg
  icons/src/scalable/apps/snap-symbolic.svg
  icons/src/scalable/mimetypes/application-vnd.snap-symbolic.svg
Labels: Area: icon theme

#2850 Fix row:selected buttons
  gtk/src/default/gtk-3.20/_common.scss
  gtk/src/default/gtk-3.20/_tweaks.scss
Labels: Area: gtk3

#2856 Split _apps into multiple files
  gtk/src/dark/gtk-3.20/apps
  gtk/src/default/gtk-3.20/_apps.scss
  gtk/src/default/gtk-3.20/apps/_evolution.scss
  gtk/src/default/gtk-3.20/apps/_firefox.scss
  gtk/src/default/gtk-3.20/apps/_geary.scss
  gtk/src/default/gtk-3.20/apps/_gedit.scss
  gtk/src/default/gtk-3.20/apps/_gnome-disks.scss
  gtk/src/default/gtk-3.20/apps/_gnome-software.scss
  gtk/src/default/gtk-3.20/apps/_gnome-terminal.scss
  gtk/src/default/gtk-3.20/apps/_gnome-todo.scss
  gtk/src/default/gtk-3.20/apps/_nautilus.scss
  gtk/src/default/gtk-3.20/apps/_nemo.scss
  gtk/src/default/gtk-3.20/apps/_tweak-tool.scss
  gtk/src/default/gtk-3.20/apps/_ubiquity.scss
  gtk/src/default/gtk-3.20/apps/_unity7.scss
  gtk/src/default/gtk-3.20/apps/_usb-creator-gtk.scss
  gtk/src/light/gtk-3.20/apps
Labels: Area: gtk3

#2859 Fix list rows orange flash when unselected
  gtk/src/default/gtk-3.20/_tweaks.scss
  gtk/src/default/gtk-4.0/_tweaks.scss
Labels: Area: gtk3, Area: gtk4

#2862 Sync gtk4 with upstream
  gtk/src/default/gtk-4.0/_colors.scss
  gtk/src/default/gtk-4.0/_common.scss
  gtk/src/default/gtk-4.0/_drawing.scss
  gtk/src/default/gtk-4.0/_headerbar.scss
  gtk/src/default/gtk-4.0/_tweaks.scss
  gtk/src/default/gtk-4.0/widgets/_calendar.scss
  gtk/src/default/gtk-4.0/widgets/_checks.scss
  gtk/src/default/gtk-4.0/widgets/_color-chooser.scss
  gtk/src/default/gtk-4.0/widgets/_dropdowns.scss
  gtk/src/default/gtk-4.0/widgets/_emoji-chooser.scss
  gtk/src/default/gtk-4.0/widgets/_level-bar.scss
  gtk/src/default/gtk-4.0/widgets/_links.scss
  gtk/src/default/gtk-4.0/widgets/_lists.scss
  gtk/src/default/gtk-4.0/widgets/_menus.scss
  gtk/src/default/gtk-4.0/widgets/_misc.scss
  gtk/src/default/gtk-4.0/widgets/_progress-bar.scss
  gtk/src/default/gtk-4.0/widgets/_scale.scss
  gtk/src/default/gtk-4.0/widgets/_sidebars.scss
  gtk/src/default/gtk-4.0/widgets/_switch.scss
  gtk/src/default/gtk-4.0/widgets/_trees.scss
  gtk/src/default/gtk-4.0/widgets/_views.scss
Labels: Area: gtk4

#2866 Sync gtk4 with upstream
  gtk/src/default/gtk-4.0/_drawing.scss
  gtk/src/default/gtk-4.0/_widgets.scss
  gtk/src/default/gtk-4.0/widgets/_buttons.scss
  gtk/src/default/gtk-4.0/widgets/_color-chooser.scss
  gtk/src/default/gtk-4.0/widgets/_dropdowns.scss
  gtk/src/default/gtk-4.0/widgets/_entries.scss
  gtk/src/default/gtk-4.0/widgets/_header-bar.scss
  gtk/src/default/gtk-4.0/widgets/_linked.scss
  gtk/src/default/gtk-4.0/widgets/_menus.scss
  gtk/src/default/gtk-4.0/widgets/_notebook.scss
  gtk/src/default/gtk-4.0/widgets/_popovers.scss
  gtk/src/default/gtk-4.0/widgets/_spin-button.scss
  gtk/src/default/gtk-4.0/widgets/_text-selection.scss
  gtk/src/default/gtk-4.0/widgets/_toolbars.scss
Labels: Area: gtk4

#2871 Make GDM widgets compliant with GS theme variant
  gnome-shell/src/gnome-shell-sass/widgets/_login-dialog.scss
Labels: Area: GNOME-shell

#2877 Fix gtk4 button mixin
  gtk/src/default/gtk-4.0/_drawing.scss
Labels: Area: gtk4
