Repository ubuntu/yaru, pull requests merged in 2021-12, with the labels that each got.

#3247 Drop treeview grey selected row tweak
  gtk/src/default/gtk-3.0/_tweaks.scss
Labels: Area: gtk3

#3252 Use $success instead of $suggested
  gtk/src/default/gtk-4.0/_colors-yaru.scss
  gtk/src/default/gtk-4.0/_defaults.scss
  gtk/src/default/gtk-4.0/_tweaks.scss
Labels: Area: gtk4

#3255 Sync check assets with upstream
  gtk/src/default/gtk-4.0/assets/bullet-small-symbolic.svg
  gtk/src/default/gtk-4.0/assets/bullet-small-symbolic.symbolic.png
  gtk/src/default/gtk-4.0/assets/bullet-small@2-symbolic.symbolic.png
  gtk/src/default/gtk-4.0/assets/bullet-symbolic.svg
  gtk/src/default/gtk-4.0/assets/bullet-symbolic.symbolic.png
  gtk/src/default/gtk-4.0/assets/bullet@2-symbolic.symbolic.png
  gtk/src/default/gtk-4.0/assets/check-small-symbolic.svg
  gtk/src/default/gtk-4.0/assets/check-small-symbolic.symbolic.png
  gtk/src/default/gtk-4.0/assets/check-small@2-symbolic.symbolic.png
  gtk/src/default/gtk-4.0/assets/check-symbolic.svg
  gtk/src/default/gtk-4.0/assets/check-symbolic.symbolic.png
  gtk/src/default/gtk-4.0/assets/check@2-symbolic.symbolic.png
  gtk/src/default/gtk-4.0/assets/dash-small-symbolic.svg
  gtk/src/default/gtk-4.0/assets/dash-small-symbolic.symbolic.png
  gtk/src/default/gtk-4.0/assets/dash-small@2-symbolic.symbolic.png
  gtk/src/default/gtk-4.0/assets/dash-symbolic.svg
  gtk/src/default/gtk-4.0/assets/dash-symbolic.symbolic.png
  gtk/src/default/gtk-4.0/assets/dash@2-symbolic.symbolic.png
Labels: Area: gtk4

#3256 Add org.gnome.Usage-symbolic symlink icon
  icons/Yaru/scalable/apps/org.gnome.Usage-symbolic.svg
  icons/src/symlinks/symbolic/apps.list
Labels: Area: icon theme

#3258 phosh: auth_sim_icon
  icons/Yaru/scalable/devices/auth-sim-symbolic.svg
  icons/Yaru/scalable/devices/auth-smartcard-symbolic.svg
  icons/Yaru/scalable/status/auth-sim-locked-symbolic.svg
  icons/Yaru/scalable/status/auth-sim-missing-symbolic.svg
  icons/src/scalable/devices/auth-sim-symbolic.svg
  icons/src/scalable/devices/auth-smartcard-symbolic.svg
  icons/src/scalable/status/auth-sim-locked-symbolic.svg
  icons/src/scalable/status/auth-sim-missing-symbolic.svg
  icons/src/scalable/status/battery-level-0-charging-symbolic.svg
Labels: Area: icon theme

#3265 Replace aubergine by orange in some icons
  icons/Yaru/16x16/apps/tweaks-app.png
  icons/Yaru/16x16@2x/apps/tweaks-app.png
  icons/Yaru/24x24/apps/software-updater.png
  icons/Yaru/24x24/apps/tweaks-app.png
  icons/Yaru/24x24@2x/apps/software-updater.png
  icons/Yaru/24x24@2x/apps/tweaks-app.png
  icons/Yaru/256x256/apps/software-updater.png
  icons/Yaru/256x256/apps/tweaks-app.png
  icons/Yaru/256x256@2x/apps/software-updater.png
  icons/Yaru/256x256@2x/apps/tweaks-app.png
  icons/Yaru/32x32/apps/software-updater.png
  icons/Yaru/32x32/apps/tweaks-app.png
  icons/Yaru/32x32@2x/apps/software-updater.png
  icons/Yaru/32x32@2x/apps/tweaks-app.png
  icons/Yaru/48x48/apps/software-updater.png
  icons/Yaru/48x48/apps/tweaks-app.png
  icons/Yaru/48x48/devices/audio-speaker-center-back-testing.svg
  icons/Yaru/48x48/devices/audio-speaker-center-testing.svg
  icons/Yaru/48x48/devices/audio-speaker-left-back-testing.svg
  icons/Yaru/48x48/devices/audio-speaker-left-side-testing.svg
  icons/Yaru/48x48/devices/audio-speaker-left-testing.svg
  icons/Yaru/48x48/devices/audio-speaker-mono-testing.svg
  icons/Yaru/48x48/devices/audio-speaker-mono.svg
  icons/Yaru/48x48/devices/audio-speaker-right-back-testing.svg
  icons/Yaru/48x48/devices/audio-speaker-right-side-testing.svg
  icons/Yaru/48x48/devices/audio-speaker-right-side.svg
  icons/Yaru/48x48/devices/audio-speaker-right-testing.svg
  icons/Yaru/48x48/devices/audio-subwoofer-testing.svg
  icons/Yaru/48x48/devices/audio-subwoofer.svg
  icons/Yaru/48x48@2x/apps/software-updater.png
  icons/Yaru/48x48@2x/apps/tweaks-app.png
  icons/src/fullcolor/default/apps/software-updater.svg
  icons/src/fullcolor/default/apps/tweaks-app.svg
  icons/src/fullcolor/default/devices/audio-speaker-center-back-testing.svg
  icons/src/fullcolor/default/devices/audio-speaker-center-testing.svg
  icons/src/fullcolor/default/devices/audio-speaker-left-back-testing.svg
  icons/src/fullcolor/default/devices/audio-speaker-left-side-testing.svg
  icons/src/fullcolor/default/devices/audio-speaker-left-testing.svg
  icons/src/fullcolor/default/devices/audio-speaker-mono-testing.svg
  icons/src/fullcolor/default/devices/audio-speaker-right-back-testing.svg
  icons/src/fullcolor/default/devices/audio-speaker-right-side-testing.svg
  icons/src/fullcolor/default/devices/audio-speaker-right-testing.svg
  icons/src/fullcolor/default/devices/audio-subwoofer-testing.svg
Labels: Area: icon theme

#3271 Drop grey selected rows
  gtk/src/default/gtk-3.0/_common.scss
  gtk/src/default/gtk-3.0/_tweaks.scss
Labels: Area: gtk3

#3274 Add new upstream symbolics
  icons/Yaru/scalable/actions/background-selected-symbolic.svg
  icons/Yaru/scalable/categories/preferences-desktop-appearance-symbolic.svg
  icons/Yaru/scalable/categories/preferences-desktop-multitasking-symbolic.svg
  icons/src/scalable/categories/preferences-desktop-appearance-symbolic.svg
  icons/src/symlinks/symbolic/actions.list
  icons/src/symlinks/symbolic/categories.list
Labels: Area: icon theme

#3276 unify all titlebuttons to a soft gray
  gtk/src/default/gtk-3.0/_tweaks.scss
  gtk/src/default/gtk-4.0/_tweaks.scss
Labels: Area: gtk3, Area: gtk4

#3278 Nautilus: keep gray rows until gtk4 port
  gtk/src/default/gtk-3.0/apps/_nautilus.scss
Labels: Area: gtk3

#3282 Add some symlinks
  icons/Yaru/scalable/actions/document-revert-rtl-symbolic.svg
  icons/Yaru/scalable/actions/format-text-direction-rtl-symbolic-rtl.svg
  icons/src/symlinks/symbolic/actions.list
Labels: Area: icon theme
